### ISSUE TITLE
print « planche » name in spacial view

### ISSUE THREAD

**Issue by adrien-github** [MickaelG/tomate_cpp#8]
Hi,
In the spacial view, could you please print the name of the « planche » (I don't know the english term, only the french, sorry) on the drawing? I name my planche « Planche 1 », « Planche 2 », etc. so in the spacial view, I know where I put my vegetables, but I can't remember the name of the Planche to fill the form! 

![screenshot_20170219_172543](https://cloud.githubusercontent.com/assets/7255104/23104155/b4c148ee-f6c8-11e6-92d6-3ddc34fc57de.png)

Thanks for your software

**Comment by MickaelG** [comment]
Hi Adrien,

Excellent idea. Thanks for the suggestion. I just added it.

Mickaël.
