### ISSUE TITLE
"Today button" and scroll in the temporal view

### ISSUE THREAD

**Issue by adrien-github** [MickaelG/tomate_cpp#9]
Hi,
I am suggesting 2 improvements in the temporal view:
– Could you please add a today button ? It could be usefull when navigating through the months for planning the garden, and then come back to the actual day
– a scroll when the mouse is pointed to the Months line may move the red timeline. The same behaviour could be implemented for the years Line to navigate through the years.

Cheers,

Adrien

**Comment by MickaelG** [comment]
Hi Adrien,

Thanks for the suggestions. Done. The "today button" is actually a small round on the "months" rule. Hope it fit your need.

Mickaël.
